// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = {
    _id: '_design/auth',
    validate_doc_update: (function(newDoc, oldDoc, userCtx) {
      var deleted, isLogged, updated;
      updated = oldDoc !== null;
      deleted = newDoc['deleted'] || newDoc['_deleted'];
      isLogged = (userCtx.name != null) && userCtx.name !== '';
      if ((deleted || updated) && !isLogged) {
        throw {
          'forbidden': 'please log in.'
        };
      }
    }).toString()
  };

}).call(this);
