// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = {
    _id: '_design/beehouses',
    views: {
      by_name: {
        map: (function(doc) {
          if (doc.type === "beehouse") {
            return emit(doc.name, doc);
          }
        }).toString()
      },
      by_apiary: {
        map: (function(doc) {
          if (doc.type === "beehouse") {
            return emit(doc.apiary_id, doc);
          }
        }).toString()
      }
    }
  };

}).call(this);
