// Generated by CoffeeScript 1.9.2
(function() {
  var Promise, config, db, dbDriver, dbServer, expect, promisify_db;

  expect = require('must');

  require('../../../openbeelab-util/javascript/objectUtils').install();

  require('../../../openbeelab-util/javascript/arrayUtils').install();

  promisify_db = require('../promisify_dbDriver');

  dbDriver = require('../mockDriver');

  Promise = require('promise');

  config = {
    database: {
      name: 'test',
      host: 'dev.openbeelab.org',
      protocol: 'http',
      port: 5984,
      auth: {
        username: 'admin',
        password: 'c0uch@dm1n'
      }
    }
  };

  dbServer = dbDriver.connectToServer(config.database);

  db = dbServer.useDb(config.database.name);

  describe("a mock db", function() {
    it("should be able to save a doc", function(done) {
      var doc;
      doc = {
        _id: 'testDoc',
        type: 'aType'
      };
      return db.create().then(function() {
        return db.save(doc);
      }).then(function() {
        return db.get('testDoc');
      }).then(function(doc) {
        doc._id.must.be('testDoc');
        doc.type.must.be('aType');
        return done();
      })["catch"](function(err) {
        return done(err);
      });
    });
    return it("can be deleted", function(done) {
      var db2;
      dbServer.deleteDb(config.database.name);
      db2 = dbServer.useDb(config.database.name);
      return db2.exists().then(function(dbExists) {
        dbExists.must.be["false"]();
        return db2.create();
      }).then(function() {
        return db2.get('testDoc');
      }).then(function(doc) {
        expect(doc).to.be.undefined();
        return done();
      })["catch"](function(err) {
        return done(err);
      });
    });
  });

}).call(this);
