// Generated by CoffeeScript 1.10.0
(function() {
  var Promise, config, db, dbDriver, expect, promisify_db, util;

  expect = require('must');

  require('../../../openbeelab-util/javascript/objectUtils').install();

  require('../../../openbeelab-util/javascript/arrayUtils').install();

  util = require('util');

  promisify_db = require('../promisify_dbDriver');

  dbDriver = require('../mockDriver');

  Promise = require('promise');

  config = {
    database: {
      name: 'test',
      host: 'dev.openbeelab.org',
      protocol: 'http',
      port: 5984,
      auth: {
        username: 'admin',
        password: 'c0uch@dm1n'
      }
    }
  };

  db = dbDriver.connectToServer(config.database).useDb(config.database.name);

  describe("a mock db", function() {
    return it("should deal with views", function(done) {
      var view;
      view = {
        _id: '_design/stands',
        views: {
          all: {
            map: (function(doc) {
              if (doc.type === "stand") {
                return emit(doc._id, doc);
              }
            }).toString()
          }
        }
      };
      return db.create().then(function() {
        return db.save(view);
      }).then(function() {
        return db.save({
          type: 'stand',
          name: 'test_stand'
        });
      }).then(function() {
        return db.save({
          type: 'location',
          name: 'test_location'
        });
      }).then(function() {
        return db.get('_design/stands/_view/all').then(function(data) {
          expect(data).to.not.be["null"]();
          expect(data.total_rows).to.not.be["null"]();
          data.total_rows.must.be(1);
          data.rows[0].key.name.must.be('test_stand');
          return done();
        })["catch"](function(err) {
          return done(err);
        });
      });
    });
  });

}).call(this);
