// Generated by CoffeeScript 1.9.2
(function() {
  var Promise, config, db, dbDriver, expect, promisify_db;

  expect = require('must');

  require('../../../openbeelab-util/javascript/objectUtils').install();

  require('../../../openbeelab-util/javascript/arrayUtils').install();

  promisify_db = require('../promisify_dbDriver');

  dbDriver = require('../mockDriver');

  Promise = require('promise');

  config = {
    database: {
      name: 'test',
      host: 'dev.openbeelab.org',
      protocol: 'http',
      port: 5984,
      auth: {
        username: 'admin',
        password: 'c0uch@dm1n'
      }
    }
  };

  db = dbDriver.connectToServer(config.database).useDb(config.database.name);

  describe("a mock db", function() {
    return it("should be able to save a doc", function(done) {
      var doc;
      doc = {
        _id: 'testDoc',
        type: 'aType'
      };
      db.create().then(function() {
        return db.save(doc);
      }).then(function() {
        return db.get('aType').then(function(doc) {
          doc._id.must.be('testDoc');
          doc.type.must.be('aType');
          return db.get('aType');
        });
      });
      return done();
    });
  });

}).call(this);
