// Generated by CoffeeScript 1.9.2
(function() {
  var createUsers, createViews;

  createViews = require('./create_views');

  createUsers = require('./create_users');

  module.exports = (function(_this) {
    return function(usersDb, db, name) {
      return db.create().then(function() {
        return createViews(db);
      }).then(function() {
        return createUsers(usersDb, db, name);
      }).then(function() {
        return db;
      });
    };
  })(this);

}).call(this);
