// Generated by CoffeeScript 1.9.2
(function() {
  var Promise, createView, fs;

  fs = require('fs');

  Promise = require('promise');

  createView = require("./create_view");

  module.exports = function(db) {
    return new Promise(function(fulfill, reject) {
      return fs.readdir(__dirname + "/views", (function(_this) {
        return function(err, filenames) {
          var promise;
          if (err) {
            reject(err);
            return;
          }
          promise = Promise.all(filenames.map(function(filename) {
            var viewName;
            viewName = filename.split(".")[0];
            return createView(db, "./views/" + viewName);
          }));
          return promise.then(function(views) {
            return fulfill(views);
          });
        };
      })(this));
    });
  };

}).call(this);
