// Generated by CoffeeScript 1.10.0
(function() {
  var cradle, promisify_db;

  cradle = require('cradle');

  promisify_db = require('./promisify_dbDriver');

  exports.connectToServer = function(config) {
    var server;
    server = new cradle.Connection(config.protocol + '://' + config.host, config.port, config);
    server.useDb = function(name) {
      return promisify_db(this.database(name));
    };
    return server;
  };

}).call(this);
