// Generated by CoffeeScript 1.9.2
(function() {
  var db;

  require('../../common/javascript/stringUtils');

  db = {};

  db.save = function(doc, callback) {
    console.log("doc saved");
    return callback();
  };

  db.get = function(id, callback) {
    var doc;
    doc = {};
    doc._id = id;
    doc._rev = "1";
    if (id.contains("sensor")) {
      doc.type = "beehouse_sensor";
      doc.measure_type = 'weight';
      doc.bias = 157;
      doc.gain = 0.176;
      doc.unit = 'kg';
      doc.pin = 5;
    }
    return callback(null, doc);
  };

  module.exports = db;

}).call(this);
